# Generated by Django 4.2 on 2023-05-06 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userRegistration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=255)),
                ('session', models.CharField(max_length=255)),
                ('registration_number', models.CharField(max_length=255)),
                ('hall', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('fathers_name', models.CharField(max_length=255)),
            ],
        ),
    ]
