# Generated by Django 4.2 on 2023-05-14 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userRegistration', '0002_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, max_length=255, upload_to='media/', verbose_name='Please select a image')),
                ('name', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('session', models.CharField(max_length=100)),
                ('registration_number', models.CharField(max_length=100)),
                ('hall', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('fathers_name', models.CharField(max_length=100)),
                ('mothers_name', models.CharField(max_length=100)),
                ('present_address', models.CharField(max_length=100)),
                ('permanent_address', models.CharField(max_length=100)),
                ('ssc_school', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
