# Generated by Django 4.2 on 2023-05-14 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userRegistration', '0003_myform_delete_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='myform',
            name='blood_group',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='myform',
            name='contact_no',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
