# Generated by Django 4.2 on 2023-05-14 19:43

import django.core.validators
from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('userRegistration', '0005_myform_gender_myform_hsc_board_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='myform',
            name='Extra_CurriCular_Activities',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Photography', 'Photography'), ('Contnet Writing', 'Contnet Writing'), ('Debating', 'Debating'), ('Graphics Design', 'Graphics Design'), ('Web Development', 'Web Development')], default='', max_length=255, validators=[django.core.validators.MaxLengthValidator(255)]),
        ),
        migrations.AddField(
            model_name='myform',
            name='hobbies_interest',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='myform',
            name='gender',
            field=models.CharField(choices=[('', 'Select Your Gender'), ('Male', 'Male'), ('Female', 'Female')], max_length=20),
        ),
        migrations.AlterField(
            model_name='myform',
            name='hsc_passing_year',
            field=models.CharField(choices=[('', 'Select Your Passing Year'), ('2016', '2016'), ('2017', '2017'), ('2018', '2018'), ('2019', '2019'), ('2020', '2020'), ('2021', '2021'), ('2022', '2022'), ('2023', '2023'), ('2024', '2024'), ('2025', '2025'), ('2026', '2026'), ('2027', '2027'), ('2028', '2028')], max_length=100),
        ),
        migrations.AlterField(
            model_name='myform',
            name='ssc_passing_year',
            field=models.CharField(choices=[('', 'Select Your Passing Year'), ('2016', '2016'), ('2017', '2017'), ('2018', '2018'), ('2019', '2019'), ('2020', '2020'), ('2021', '2021'), ('2022', '2022'), ('2023', '2023'), ('2024', '2024'), ('2025', '2025'), ('2026', '2026'), ('2027', '2027'), ('2028', '2028')], max_length=100),
        ),
    ]
