# Generated by Django 4.2 on 2023-05-14 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userRegistration', '0007_myform_information_tech_interest_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myform',
            name='ssc_school',
        ),
    ]
