# Generated by Django 4.2 on 2023-05-14 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userRegistration', '0008_remove_myform_ssc_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myform',
            name='blood_group',
            field=models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O+', 'O+')], max_length=10),
        ),
    ]
