# Generated by Django 4.2 on 2023-05-17 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userRegistration', '0009_alter_myform_blood_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myform',
            name='blood_group',
            field=models.CharField(choices=[('', 'Select Your Blood Group'), ('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O+', 'O+')], max_length=10),
        ),
    ]
