# Generated by Django 4.2 on 2023-05-17 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userRegistration', '0010_alter_myform_blood_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='myform',
            name='situation',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Pending', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='myform',
            name='blood_group',
            field=models.CharField(choices=[('', 'Select Your Blood Group'), ('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=10),
        ),
        migrations.AlterField(
            model_name='myform',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='myform',
            name='registration_number',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
